insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve1', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve2', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve3', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve4', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve5', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve6', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve7', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve8', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve9', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve10', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve11', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve12', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve13', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve14', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
insert into UTILISATEUR (utilisateur_id, login, password, archive, super) select max(utilisateur_id)+1, 'eleve15', md5('formation'), 0, 0 from UTILISATEUR;
insert into PLATEFORME_ADMINISTRATEUR select plateforme_id, (select max(utilisateur_id) from UTILISATEUR) from PLATEFORME;
