CREATE TABLE PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID NUMBER(22) NOT NULL,
                    PRELEVEMENT_ID NUMBER(22) UNIQUE NOT NULL,
                    CONTEXTE_ID NUMBER(2) NOT NULL,
        primary key (PRELEVEMENT_DELEGATE_ID),
        constraint FK_PREL_DEL_CONTEXTE_ID foreign key (CONTEXTE_ID) 
            references CONTEXTE (CONTEXTE_ID),
        constraint FK_PREL_DEL_PRELEVEMENT_ID foreign key (PRELEVEMENT_ID) 
            references PRELEVEMENT (PRELEVEMENT_ID));
        

CREATE TABLE PRELEVEMENT_SERO (PRELEVEMENT_DELEGATE_ID NUMBER(22) NOT NULL, 
                LIBELLE VARCHAR2(300), 
        PRIMARY KEY (PRELEVEMENT_DELEGATE_ID), 
        CONSTRAINT FK_PREL_SERO_PREL_DEL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
            REFERENCES PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID));

CREATE TABLE PROTOCOLE (PROTOCOLE_ID NUMBER(3) NOT NULL, 
            NOM VARCHAR2(200) NOT NULL,
            DESCRIPTION VARCHAR2(4000),
            PLATEFORME_ID NUMBER(22),
        PRIMARY KEY (PROTOCOLE_ID),
        CONSTRAINT FK_PROTOCOLE_PLATEFORME_ID FOREIGN KEY (PLATEFORME_ID) 
            REFERENCES PLATEFORME (PLATEFORME_ID));

CREATE TABLE PRELEVEMENT_SERO_PROTOCOLE (PRELEVEMENT_DELEGATE_ID NUMBER(22) NOT NULL, 
                PROTOCOLE_ID NUMBER(3) NOT NULL,
        PRIMARY KEY (PRELEVEMENT_DELEGATE_ID, PROTOCOLE_ID),
        CONSTRAINT FK_PREL_PROTO_PREL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
            REFERENCES PRELEVEMENT_SERO (PRELEVEMENT_DELEGATE_ID), 
        CONSTRAINT FK_PREL_PROTO_PROTO_ID FOREIGN KEY (PROTOCOLE_ID) 
            REFERENCES PROTOCOLE (PROTOCOLE_ID));

CREATE TABLE PRELEVEMENT_XENO (PRELEVEMENT_DELEGATE_ID NUMBER(22) NOT NULL, 
                SOURIS VARCHAR2(50), 
        PRIMARY KEY (PRELEVEMENT_DELEGATE_ID), 
        CONSTRAINT FK_PREL_XENO_PREL_DEL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
            REFERENCES PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID));

CREATE TABLE MALADIE_DELEGATE (MALADIE_DELEGATE_ID NUMBER(22) NOT NULL,
                    MALADIE_ID NUMBER(22) UNIQUE NOT NULL,
                    CONTEXTE_ID NUMBER(2) NOT NULL,
        primary key (MALADIE_DELEGATE_ID),
        constraint FK_MALADIE_DEL_CONTEXTE_ID foreign key (CONTEXTE_ID) 
            references CONTEXTE (CONTEXTE_ID),
        constraint FK_MALADIE_DEL_MALADIE_ID foreign key (MALADIE_ID) 
            references MALADIE (MALADIE_ID));

CREATE TABLE MALADIE_SERO (MALADIE_DELEGATE_ID NUMBER(22) NOT NULL, 
                DIAGNOSTIC CHAR(1) NOT NULL, 
        PRIMARY KEY (MALADIE_DELEGATE_ID), 
        CONSTRAINT FK_MAL_SERO_MAL_DEL_ID FOREIGN KEY (MALADIE_DELEGATE_ID) 
            REFERENCES MALADIE_DELEGATE (MALADIE_DELEGATE_ID));

create index fk_prel_del_contexte_idx on PRELEVEMENT_DELEGATE (CONTEXTE_ID); 
create index fk_prel_del_prel_idx on PRELEVEMENT_DELEGATE (PRELEVEMENT_ID); 
create index fk_prel_sero_prel_del_idx on PRELEVEMENT_SERO (PRELEVEMENT_DELEGATE_ID);
create index fk_protocole_pf_idx on PROTOCOLE (PLATEFORME_ID);
create index fk_prel_proto_prel_idx on PRELEVEMENT_SERO_PROTOCOLE (PRELEVEMENT_DELEGATE_ID);
create index fk_prel_proto_proto_idx on PRELEVEMENT_SERO_PROTOCOLE (PROTOCOLE_ID);
create index fk_prel_xeno_prel_id on PRELEVEMENT_XENO (PRELEVEMENT_DELEGATE_ID);
create index fk_maladie_del_contexte_idx on MALADIE_DELEGATE(CONTEXTE_ID);
create index fk_maladie_del_maladie_idx on MALADIE_DELEGATE(MALADIE_ID);
create index fk_mal_sero_mal_del_idx on MALADIE_SERO (MALADIE_DELEGATE_ID);        

