CREATE TABLE PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID INT(10) NOT NULL,
					PRELEVEMENT_ID INT(10) UNIQUE NOT NULL,
					CONTEXTE_ID INT(2) NOT NULL,
		primary key (PRELEVEMENT_DELEGATE_ID),
		constraint FK_PREL_DEL_CONTEXTE_ID foreign key (CONTEXTE_ID) 
			references CONTEXTE (CONTEXTE_ID),
		constraint FK_PREL_DEL_PRELEVEMENT_ID foreign key (PRELEVEMENT_ID) 
			references PRELEVEMENT (PRELEVEMENT_ID)) ENGINE=InnoDB;
		

CREATE TABLE PRELEVEMENT_SERO (PRELEVEMENT_DELEGATE_ID INT(10) NOT NULL, 
				LIBELLE VARCHAR(300), 
		PRIMARY KEY (PRELEVEMENT_DELEGATE_ID), 
		CONSTRAINT FK_PREL_SERO_PREL_DEL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
			REFERENCES PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID)) ENGINE=InnoDB;

CREATE TABLE PROTOCOLE (PROTOCOLE_ID INT(3) NOT NULL, 
			NOM VARCHAR(200) NOT NULL,
			DESCRIPTION TEXT,
			PLATEFORME_ID INT(10),
		PRIMARY KEY (PROTOCOLE_ID),
		CONSTRAINT FK_PROTOCOLE_PLATEFORME_ID FOREIGN KEY (PLATEFORME_ID) 
			REFERENCES PLATEFORME (PLATEFORME_ID)) ENGINE=InnoDB;

CREATE TABLE PRELEVEMENT_SERO_PROTOCOLE (PRELEVEMENT_DELEGATE_ID INT(10) NOT NULL, 
				PROTOCOLE_ID INT(10) NOT NULL,
		PRIMARY KEY (PRELEVEMENT_DELEGATE_ID, PROTOCOLE_ID),
		CONSTRAINT FK_PREL_PROTO_PREL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
			REFERENCES PRELEVEMENT_SERO (PRELEVEMENT_DELEGATE_ID), 
		CONSTRAINT FK_PREL_PROTO_PROTO_ID FOREIGN KEY (PROTOCOLE_ID) 
			REFERENCES PROTOCOLE (PROTOCOLE_ID)) ENGINE=InnoDB;

CREATE TABLE PRELEVEMENT_XENO (PRELEVEMENT_DELEGATE_ID INT(10) NOT NULL, 
				SOURIS VARCHAR(50), 
		PRIMARY KEY (PRELEVEMENT_DELEGATE_ID), 
		CONSTRAINT FK_PREL_XENO_PREL_DEL_ID FOREIGN KEY (PRELEVEMENT_DELEGATE_ID) 
			REFERENCES PRELEVEMENT_DELEGATE (PRELEVEMENT_DELEGATE_ID)) ENGINE=InnoDB;

CREATE TABLE MALADIE_DELEGATE (MALADIE_DELEGATE_ID INT(10) NOT NULL,
					MALADIE_ID INT(10) UNIQUE NOT NULL,
					CONTEXTE_ID INT(2) NOT NULL,
		primary key (MALADIE_DELEGATE_ID),
		constraint FK_MALADIE_DEL_CONTEXTE_ID foreign key (CONTEXTE_ID) 
			references CONTEXTE (CONTEXTE_ID),
		constraint FK_MALADIE_DEL_MALADIE_ID foreign key (MALADIE_ID) 
			references MALADIE (MALADIE_ID)) ENGINE=InnoDB;

CREATE TABLE MALADIE_SERO (MALADIE_DELEGATE_ID INT(10) NOT NULL, 
				DIAGNOSTIC CHAR(1) NOT NULL, 
		PRIMARY KEY (MALADIE_DELEGATE_ID), 
		CONSTRAINT FK_MAL_SERO_MAL_DEL_ID FOREIGN KEY (MALADIE_DELEGATE_ID) 
			REFERENCES MALADIE_DELEGATE (MALADIE_DELEGATE_ID)) ENGINE=InnoDB;


CREATE TABLE CHAMP_ENTITE_CONTEXTE (CHAMP_ENTITE_ID INT(10) NOT NULL, 
					CONTEXTE_ID INT(10) NOT NULL,
		PRIMARY KEY (CHAMP_ENTITE_ID, CONTEXTE_ID), 
		CONSTRAINT FK_CHP_ENT_CONT_CHP_ID FOREIGN KEY (CHAMP_ENTITE_ID) 
			REFERENCES CHAMP_ENTITE (CHAMP_ENTITE_ID),
		CONSTRAINT FK_CHP_ENT_CONT_CONT_ID FOREIGN KEY (CONTEXTE_ID) 
			REFERENCES CONTEXTE (CONTEXTE_ID)) ENGINE=InnoDB;

-- CHAMPS ENTITES
-- insert into ENTITE values (63, 'Delegate', 1, 0);
-- delete from ENTITE where entite_id=17;
-- insert into ENTITE values (64, 'Protocole', 1, 0);
-- insert into CHAMP_ENTITE values (250, 'Delegate', 1, 0, 0, NULL, 2, 0, NULL);
-- champ entite prelevement
-- insert into CHAMP_ENTITE values (251, 'Delegate.protocoles', 10, 1, 0, NULL, 2, 1, NULL);
-- insert into CHAMP_ENTITE_CONTEXTE values (251, 1);
-- insert into CHAMP_ENTITE_BLOC values (251, 1, 4);
-- complement diagnostic
-- insert into CHAMP_ENTITE values (252, 'Libelle', 1, 1, 0, NULL, 2, 1, NULL);
-- insert into CHAMP_ENTITE_CONTEXTE values (252, 1);
-- insert into CHAMP_ENTITE_BLOC values (252, 3, 12);

-- champ entite protocole
-- insert into CHAMP_ENTITE values (253, 'ProtocoleId', 5, 0, 1, NULL, 64, 0, NULL);
-- insert into CHAMP_ENTITE values (254, 'Nom', 1, 0, 0, NULL, 64, 0, NULL);
-- insert into CHAMP_ENTITE values (255, 'Description', 6, 1, 0, NULL, 64, 0, NULL);

-- champ entite delegate
-- insert into CHAMP_ENTITE values (256, 'Libelle', 1, 1, 0, NULL, 63, 1, NULL);
-- insert into CHAMP_ENTITE values (257, 'Protocoles', 1, 1, 0, NULL, 63, 1, 254);









